### PR TITLE
Webmozart assertions

### LINKED ISSUE #168: Settings variables in assert()
https://github.com/simplesamlphp/saml2/blob/94d61b2f5eeb7aa96784c87f9d58b8c7992fbc0f/src/SAML2/XML/mdui/DiscoHints.php#L156-L164

This section doesn't work when PHP's zend.assertions option is < 1, which is the case if you're using the php.ini-production file which ships with PHP 7.2 (or anything derived from it).  Because PHP doesn't execute the assert(), the local variables are never set, so the if condition can never be true.

This affects SimpleSAMLphp 1.17.1: even if I set DiscoHints in metadata/saml20-idp-hosted.php, they simply aren't included in the metadata that's output.

### PR DESCRIPTION
**Pull request by tvdijen**
Fixes and closes #168

### CODE REVIEW

File: src/SAML2/AuthnRequest.php [hunk 1]
```diff
@@ -660,10 +662,8 @@ public function getRequestedAuthnContext()
      * @param array $requestedAuthnContext The RequestedAuthnContext.
      * @return void
      */
-    public function setRequestedAuthnContext($requestedAuthnContext)
+    public function setRequestedAuthnContext(array $requestedAuthnContext)
```
Comment (jaimeperez) [inline src/SAML2/AuthnRequest.php]: This is not something we can add in the 3.x branch, right? Type hinting with scalar types is not available in PHP 5.x.

File: src/SAML2/Message.php [hunk 2]
```diff
@@ -226,10 +228,8 @@ private function validateSignature(\DOMElement $xml)
      * @param mixed    $data     The data that should be included as the first parameter to the function
      * @return void
      */
-    public function addValidator($function, $data)
+    public function addValidator(callable $function, $data)
```
Comment (jaimeperez) [inline src/SAML2/Message.php]: Same here, I think callable is not available for type hinting in PHP 5.x.

File: src/SAML2/SignedElementHelper.php [hunk 3]
```diff
@@ -77,10 +77,8 @@ protected function __construct(\DOMElement $xml = null)
      * @param mixed    $data     The data that should be included as the first parameter to the function.
      * @return void
      */
-    public function addValidator($function, $data)
+    public function addValidator(callable $function, $data)
```
Comment (jaimeperez) [inline src/SAML2/SignedElementHelper.php]: ⬆️

File: src/SAML2/XML/md/EntityDescriptor.php [hunk 4]
```diff
@@ -450,16 +451,16 @@ public function addAdditionalMetadataLocation(AdditionalMetadataLocation $additi
...
-        assert(is_array($this->getContactPerson()));
-        assert(is_array($this->getAdditionalMetadataLocation()));
+        Assert::string($this->getEntityID());
+        Assert::nullOrString($this->getID());
+        Assert::nullOrInteger($this->getValidUntil());
+        Assert::nullOrString($this->getCacheDuration());
+        Assert::isArray($this->getExtensions());
+        Assert::isArray($this->getRoleDescriptor());
+        Assert::nullOrIsInstanceOf($this->getAffiliationDescriptor());
+        Assert::nullOrIsInstance($this->getOrganization());
```
Comment (jaimeperez) [inline src/SAML2/XML/md/EntityDescriptor.php]: Does `nullOrIsInstance()` exist, or is this a typo?

File: src/SAML2/AuthnRequest.php (hunk 1 above)
Comment (tvdijen) [reply src/SAML2/AuthnRequest.php]: http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration

Since 5.1

File: src/SAML2/Message.php (hunk 2 above)
Comment (tvdijen) [reply src/SAML2/Message.php]: Since 5.4
http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration

File: src/SAML2/SignedElementHelper.php (hunk 3 above)
Comment (tvdijen) [reply src/SAML2/SignedElementHelper.php]: Since 5.4
http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration

File: src/SAML2/XML/md/EntityDescriptor.php (hunk 4 above)
Comment (tvdijen) [reply src/SAML2/XML/md/EntityDescriptor.php]: That's a typo, thanks!
